#!/usr/bin/env bash

set -e

case "$(uname -s)" in
    Linux*)               MACHINE=Linux;;
    Darwin*)              MACHINE=Mac;;
    CYGWIN*|MINGW*|MSYS*) MACHINE=Windows;;
    *)                    MACHINE=Unknown;;
esac

export MACHINE="${MACHINE}"

if [[ ${MACHINE} == Windows ]]; then
    exec winpty ant $@
fi

TOOL=$1

if [[ "${TOOL}" == "" ]]; then
    TOOL=help
else
    shift
fi

if [[ ! -f "$(cd "$(echo "${BASH_SOURCE[0]%/*}")" && pwd)/ant-${TOOL}" ]]; then
    echo "Tool '${TOOL}' does not exist!"
    echo ""
    TOOL=help
fi

exec ant-${TOOL} $@
