#!/usr/bin/env bash

set -e

if [[ "$(docker ps -q -f name=httpd)" ]]; then
    if [[ $(cat ~/.ant/.ant-dev-lock) != $(pwd) ]]; then
        echo -e "Warning! Current containers were created from different directory."
        if [[ -f "docker-compose.yml" ]]; then
            echo -e "Found docker-compose.yml in current directory. Will destroy old containers and create new ones."
            ant-down
            docker-compose up -d
            $(pwd) > ~/.ant/.ant-dev-lock
        fi
    fi
else
    if [[ "$(docker ps -aq -f status=exited -f name=httpd)" ]]; then
        echo -e "Removing stopped containers"
        ant-down
    fi
    docker-compose up -d
    $(pwd) > ~/.ant/.ant-dev-lock
fi
