#!/usr/bin/env bash

set -e

if [[ ! "$(docker ps -q -f name=database)" ]]; then
    ant up
fi

DB=""
FILE=$1

if [[ $2 != "" ]]; then
	DB=$1
	FILE=$2
fi

exec docker exec -i database mysql -uroot -proot ${DB} < ${FILE}
