#!/usr/bin/env bash

set -e

if [[ ! "$(docker ps -q -f name=database)" ]]; then
    ant-up
fi

DB=$1
RESULT_PATH="."

if [[ $2 != "" ]]; then
    RESULT_PATH="$2"
fi

exec docker exec \
    database mysqldump --add-drop-table --add-locks --compact --disable-keys --extended-insert --insert-ignore --no-create-db -uroot ${DB} > ${RESULT_PATH}/${DB}.sql
