#!/usr/bin/env bash

set -e

DOCKER=$(docker -v | grep -Eom 1 '[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}')
echo "Docker:         ${DOCKER}"

DOCKER_COMPOSE=$(docker-compose -v | grep -Eom 1 '[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}')
echo "Docker-compose: ${DOCKER_COMPOSE}"

APACHE_ID=$(docker run --rm -d sirpole/ant-dev:httpd)
trap "docker stop ${APACHE_ID}" 0 1 2 3 9 15
APACHE=$(docker exec ${APACHE_ID} httpd -v | grep -Eom 1 '[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}')
echo "Apache:         ${APACHE}"

PHP72=$(docker run --rm sirpole/ant-dev:php-7.2 php -v | grep -Eom 1 '[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}')
echo "PHP 7.2:        ${PHP72}"

PHP71=$(docker run --rm sirpole/ant-dev:php-7.1 php -v | grep -Eom 1 '[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}')
echo "PHP 7.1:        ${PHP71}"

PHP56=$(docker run --rm sirpole/ant-dev:php-5.6 php -v | grep -Eom 1 '[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}')
echo "PHP 5.6:        ${PHP56}"

MYSQL=$(docker run --rm -e MYSQL_ALLOW_EMPTY_PASSWORD=1 mysql --version | grep -Eom 1 '[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}')
echo "MySQL:          ${MYSQL}"

NODE=$(docker run --rm sirpole/ant-dev:node node -v | grep -Eom 1 '[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}')
echo "Node.js:        ${NODE}"

NPM=$(docker run --rm sirpole/ant-dev:node npm -v | grep -Eom 1 '[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}')
echo "npm:            ${NPM}"

REDIS=$(docker run --rm redis:alpine redis-server --version | grep -Eom 1 '[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}' | head -n1)
echo "Redis:          ${REDIS}"

COMPOSER=$(docker run --rm composer composer --version | grep -Eom 1 '[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}')
echo "Composer:       ${COMPOSER}"
