#!/usr/bin/env bash

set -e

DIR=$(cd "$(echo "${BASH_SOURCE[0]%/*}")/../../docker" && pwd)

docker build --no-cache -t sirpole/ant-dev:chrome ${DIR}/chrome
docker build --no-cache -t sirpole/ant-dev:httpd ${DIR}/httpd
docker build --no-cache -t sirpole/ant-dev:php-7.3 ${DIR}/php/7.3
docker build --no-cache -t sirpole/ant-dev:php-7.2 ${DIR}/php/7.2
docker build --no-cache -t sirpole/ant-dev:php-7.1 ${DIR}/php/7.1
docker build --no-cache -t sirpole/ant-dev:php-5.6 ${DIR}/php/5.6
docker build --no-cache -t sirpole/ant-dev:docker ${DIR}/docker
