#!/usr/bin/env bash

set -e

if [[ ! "$(docker ps -q -f name=database)" ]]; then
    ant-up
fi

DB=""
FILE=$1

if [[ $2 != "" ]]; then
	DB=$1
	FILE=$2
    docker exec \
        --interactive \
        --tty \
        database mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS ${DB}"
fi

exec docker exec \
    --interactive \
    --tty \
    database mysql -uroot -proot ${DB} < ${FILE}
