#!/usr/bin/env bash

set -e

docker push sirpole/ant-dev:chrome
docker push sirpole/ant-dev:httpd
docker push sirpole/ant-dev:nginx
docker push sirpole/ant-dev:php-7.3
docker push sirpole/ant-dev:php-7.2
docker push sirpole/ant-dev:php-7.1
docker push sirpole/ant-dev:php-5.6
docker push sirpole/ant-dev:docker
