#!/usr/bin/env bash

set -e

DIR="$(cd "$(echo "${BASH_SOURCE[0]%/*}")" && pwd)"
RET=0
crontab -l 2>/dev/null | grep -q 'ant selfupdate' >/dev/null 2>&1 || RET=$?
if [[ ${RET} != 0 ]]; then
    (crontab -l 2>/dev/null; echo " 0 10 * * * ${DIR}/ant selfupdate") | crontab -
fi

cd ${DIR}/../..

BRANCH=$(git rev-parse --abbrev-ref HEAD)

git fetch --all
git stash save
git checkout master --force
git reset --hard origin/master
git checkout ${BRANCH} --force
git stash pop

docker pull sirpole/ant-dev:chrome
docker pull sirpole/ant-dev:httpd
docker pull sirpole/ant-dev:node
docker pull sirpole/ant-dev:php-7.2
docker pull sirpole/ant-dev:php-7.1
docker pull sirpole/ant-dev:php-5.6
docker pull mysql
docker pull phpmyadmin/phpmyadmin
docker pull redis:alpine
docker pull erikdubbelboer/phpredisadmin
docker pull composer
docker system prune -f

$(date '+%s') > ~/.ant/.ant-dev-lastupdate

exit
