#!/usr/bin/env bash

set -e

if [[ ! "$(docker ps -q -f name=php)" ]]; then
    ant-up
fi

exec docker exec \
    --interactive \
    --tty \
    --user $(id -u):$(id -g) \
    php php index.php migrations:migrate
