#!/usr/bin/env bash

set -e

exec docker run \
  --rm \
  --interactive \
  --tty \
  --user $(id -u):$(id -g) \
  --name composer \
  --volume $(pwd):/app \
  --volume ~/.ant/composer:/tmp \
  composer "$@"
