#!/usr/bin/env bash

set -e

if [[ $(ant-machine) == Windows ]]; then
    exec composer.bat $@
fi

exec docker run \
  --rm \
  --interactive \
  --tty \
  --user $(id -u):$(id -g) \
  --name composer \
  --network ant-dev \
  --volume $(pwd):/app \
  --volume ~/.ant/composer:/tmp \
  composer --ignore-platform-reqs "$@"
