#!/usr/bin/env bash

set -e

if [ "$(docker ps -q -f name=web)" ]; then
    if [[ $(docker inspect -f "{{range .Mounts}}{{if eq .Destination \"/var/www\"}}{{.Source}}{{end}}{{end}}" web)!=$(pwd) ]]; then
        echo -e "Warning! Current containers were created from different directory."
        if [[ -f "docker-compose.yml" ]]; then
            echo -e "Found docker-compose.yml in current directory. Will destroy old containers and create new ones."
            dcdown > /dev/null
            docker-compose up -d
        fi
    fi
else
    if [[ "$(docker ps -aq -f status=exited -f name=web)" ]]; then
        echo -e "Removing stopped containers"
        dcdown > /dev/null
    fi
    docker-compose up -d
fi

if [[ $1 = -i ]]; then
    USER=ant
    if [[ $(whoami) == root ]]; then
        USER=root
    fi
    exec docker exec -it -u ${USER} web bash
fi
