#!/usr/bin/env bash

case "$(uname -s)" in
    Linux*)               MACHINE=Linux;;
    Darwin*)              MACHINE=Mac;;
    CYGWIN*|MINGW*|MSYS*) MACHINE=Windows;;
    *)                    MACHINE=Unknown;;
esac

printf ${MACHINE}
