#!/usr/bin/env bash

set -e

if [[ $(ant-machine) == Windows ]]; then
    exec mysql.bat $@
fi

if [[ ! "$(docker ps -q -f name=database)" ]]; then
    ant up
fi

exec docker exec \
    --interactive \
    --tty \
    database mysql -uroot "$@"
