#!/usr/bin/env bash

set -e

if [[ $(ant-machine) == Windows ]]; then
    exec node.bat $@
fi

if [[ "$(docker ps -q -f name=node)" ]]; then
    exec docker exec \
        --interactive \
        --tty \
        node node "$@"
else
    exec docker run \
        --rm \
        --interactive \
        --tty \
        --user $(id -u):$(id -g) \
        --name node \
        --network ant-dev \
        --publish 3000:3000 \
        --volume $(pwd):/app \
        --volume ~/.ant/npm:/tmp \
        sirpole/ant-dev:node node "$@"
fi
