#!/usr/bin/env bash

set -e

if [[ $(ant-machine) == Windows ]]; then
    exec php.bat $@
fi

if [[ ! "$(docker ps -q -f name=php)" ]]; then
    ant up
fi

exec docker exec \
    --interactive \
    --tty \
    --user $(id -u):$(id -g) \
    php php "$@"
