#!/usr/bin/env bash

set -e

exec docker run \
  --rm \
  --interactive \
  --tty \
  --user $(id -u):$(id -g) \
  --name node \
  --volume $(pwd):/app \
  --workdir /app \
  --volume ~/.ant/npm:/tmp \
  --env npm_config_cache=/tmp \
  node:8-alpine npx sass-lint "$@"
