#!/usr/bin/env bash

set -e

if [[ $(ant-machine) == Windows ]]; then
    exec tldr.bat $@
fi

exec docker run \
  --rm \
  --interactive \
  --tty \
  --user $(id -u):$(id -g) \
  --name node \
  --volume $(pwd):/app \
  --volume ~/.ant/npm:/tmp \
  sirpole/ant-dev:node tldr "$@"
