#!/usr/bin/env bash

set -e

USER=root
if [[ $(stat -c "%u" .) != 0 ]]; then
	useradd -s /bin/bash -u $(stat -c "%u" .) -o -m ant
	USER=ant
	chown ${USER} .
	export APACHE_RUN_USER=${USER}
	export APACHE_RUN_GROUP=${USER}
fi

su ${USER} -c "mkdir -p ~/.ssh"
su ${USER} -c "echo 'IdentityFile /.ssh-host/id_rsa' > ~/.ssh/config"
su ${USER} -c "ssh-keyscan git.antstudio.cz >> ~/.ssh/known_hosts"
if [[ ${GITHUB_KEY} ]]; then
	su ${USER} -c "composer config --global github-oauth.github.com ${GITHUB_KEY}"
fi
su ${USER} -c "mkdir -p log"

: > log/apache.access.log
: > log/apache.error.log
: > log/php.error.log

exec apache2-foreground
